METHOD: BiMC
MODEL:
  BACKBONE:
    NAME: ViT-B/16

TRAINER:
  BiMC:
    PREC: fp32
    VISION_CALIBRATION: True
    LAMBDA_I: 0.2
    TAU: 64
    TEXT_CALIBRATION: True
    LAMBDA_T: 0.7
    GAMMA_BASE: 1.0
    GAMMA_INC: 1.0
    USING_ENSEMBLE: True
