SEED: 42
DATASET:
  NAME: fruits
  ROOT: C:\fruits_data
  GPT_PATH: description/fruits_prompts_full.json
  NUM_CLASSES: 24
  NUM_INIT_CLS: 10
  NUM_INC_CLS: 2
  NUM_BASE_SHOT: 200
  NUM_INC_SHOT: 50

  BETA: 0.7
  ENSEMBLE_ALPHA: 0.5

DATALOADER:
  TRAIN:
    BATCH_SIZE_BASE: 64
    BATCH_SIZE_INC: 16
  TEST:
    BATCH_SIZE: 64
  NUM_WORKERS: 16

DEVICE:
  DEVICE_NAME: "cuda"
  GPU_ID: "0;"
